use serde::{Deserialize, Serialize};

#[derive(Clone, PartialEq, Eq, Serialize, Deserialize, Debug)]
pub enum SkillBranch {
    Warrior,
    Mage,
    Rogue,
    Universal,
}

#[derive(Clone, PartialEq, Eq, Serialize, Deserialize, Debug)]
pub enum SkillEffect {
    AttackMult(u32),        // percent multiplier (100 = normal)
    AoeDamage(i32),
    Heal(i32),
    MpHeal(i32),
    Shield(i32, u32),       // shield amount, turns
    DotPoison(i32, u32),    // damage per turn, turns
    Stun(u32),              // turns
    TeleportStrike,
    LifeSteal(u32),         // percent of damage
    SummonSkeleton,
    DoubleAttack,
    CritBoost(u32),         // percent crit rate boost
    MpReduce(u32),          // reduces mp costs
    ExpBoost(u32),          // exp multiplier
    LuckBoost(u32),
    PassiveAttackBoost(i32),
    PassiveDefBoost(i32),
    PassiveHpBoost(i32),
    PassiveMpBoost(i32),
    PassiveRegenHp(i32),
    PassiveRegenMp(i32),
}

#[derive(Clone, Serialize, Deserialize, Debug)]
pub struct Skill {
    pub id: usize,
    pub name: String,
    pub branch: SkillBranch,
    pub level: u8,
    pub max_level: u8,
    pub mp_cost: i32,
    pub cooldown: u32,
    pub current_cooldown: u32,
    pub is_passive: bool,
    pub effect: SkillEffect,
    pub description: String,
    pub prerequisite: Option<usize>,
    pub unlocked: bool,
    pub learned: bool,
}

impl Skill {
    pub fn can_use(&self, current_mp: i32) -> bool {
        !self.is_passive && self.learned && self.current_cooldown == 0 && current_mp >= self.mp_cost
    }
}

pub fn all_skills() -> Vec<Skill> {
    vec![
        // ===== WARRIOR BRANCH =====
        Skill {
            id: 0,
            name: "Power Strike".to_string(),
            branch: SkillBranch::Warrior,
            level: 1,
            max_level: 5,
            mp_cost: 5,
            cooldown: 2,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::AttackMult(175),
            description: "A powerful strike dealing 175% damage.".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
        },
        Skill {
            id: 1,
            name: "Iron Wall".to_string(),
            branch: SkillBranch::Warrior,
            level: 1,
            max_level: 5,
            mp_cost: 8,
            cooldown: 5,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::Shield(30, 5),
            description: "Erect a shield absorbing 30 damage for 5 turns.".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
        },
        Skill {
            id: 2,
            name: "Berserker Rage".to_string(),
            branch: SkillBranch::Warrior,
            level: 1,
            max_level: 3,
            mp_cost: 15,
            cooldown: 8,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::CritBoost(50),
            description: "Enter a rage: +50% crit rate for 5 turns.".to_string(),
            prerequisite: Some(0),
            unlocked: false,
            learned: false,
        },
        Skill {
            id: 3,
            name: "Veteran's Body".to_string(),
            branch: SkillBranch::Warrior,
            level: 1,
            max_level: 5,
            mp_cost: 0,
            cooldown: 0,
            current_cooldown: 0,
            is_passive: true,
            effect: SkillEffect::PassiveHpBoost(50),
            description: "Passively increases max HP by 50.".to_string(),
            prerequisite: Some(1),
            unlocked: false,
            learned: false,
        },
        Skill {
            id: 4,
            name: "Warlord's Fury".to_string(),
            branch: SkillBranch::Warrior,
            level: 1,
            max_level: 3,
            mp_cost: 25,
            cooldown: 12,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::AoeDamage(40),
            description: "Unleash a shockwave dealing 40 damage to all nearby enemies.".to_string(),
            prerequisite: Some(2),
            unlocked: false,
            learned: false,
        },
        // ===== MAGE BRANCH =====
        Skill {
            id: 5,
            name: "Fireball".to_string(),
            branch: SkillBranch::Mage,
            level: 1,
            max_level: 5,
            mp_cost: 10,
            cooldown: 1,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::AoeDamage(25),
            description: "Launch a fireball dealing 25 magic damage to nearby enemies.".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
        },
        Skill {
            id: 6,
            name: "Mana Shield".to_string(),
            branch: SkillBranch::Mage,
            level: 1,
            max_level: 5,
            mp_cost: 20,
            cooldown: 6,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::Shield(50, 8),
            description: "Conjure a mana barrier absorbing 50 damage.".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
        },
        Skill {
            id: 7,
            name: "Arcane Mastery".to_string(),
            branch: SkillBranch::Mage,
            level: 1,
            max_level: 5,
            mp_cost: 0,
            cooldown: 0,
            current_cooldown: 0,
            is_passive: true,
            effect: SkillEffect::PassiveMpBoost(40),
            description: "Increases max MP by 40.".to_string(),
            prerequisite: Some(5),
            unlocked: false,
            learned: false,
        },
        Skill {
            id: 8,
            name: "Poison Cloud".to_string(),
            branch: SkillBranch::Mage,
            level: 1,
            max_level: 5,
            mp_cost: 18,
            cooldown: 4,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::DotPoison(8, 5),
            description: "Summon a poison cloud dealing 8 damage/turn for 5 turns.".to_string(),
            prerequisite: Some(5),
            unlocked: false,
            learned: false,
        },
        Skill {
            id: 9,
            name: "Arcane Surge".to_string(),
            branch: SkillBranch::Mage,
            level: 1,
            max_level: 3,
            mp_cost: 30,
            cooldown: 10,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::AttackMult(300),
            description: "Channel all magic into one devastating 300% damage spell.".to_string(),
            prerequisite: Some(7),
            unlocked: false,
            learned: false,
        },
        // ===== ROGUE BRANCH =====
        Skill {
            id: 10,
            name: "Shadow Strike".to_string(),
            branch: SkillBranch::Rogue,
            level: 1,
            max_level: 5,
            mp_cost: 6,
            cooldown: 2,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::TeleportStrike,
            description: "Blink behind the enemy and deal a critical hit.".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
        },
        Skill {
            id: 11,
            name: "Blade Dance".to_string(),
            branch: SkillBranch::Rogue,
            level: 1,
            max_level: 5,
            mp_cost: 10,
            cooldown: 3,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::DoubleAttack,
            description: "Attack twice in one turn.".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
        },
        Skill {
            id: 12,
            name: "Lifesteal".to_string(),
            branch: SkillBranch::Rogue,
            level: 1,
            max_level: 5,
            mp_cost: 0,
            cooldown: 0,
            current_cooldown: 0,
            is_passive: true,
            effect: SkillEffect::LifeSteal(20),
            description: "Passively steal 20% of damage dealt as HP.".to_string(),
            prerequisite: Some(10),
            unlocked: false,
            learned: false,
        },
        Skill {
            id: 13,
            name: "Venomous Blade".to_string(),
            branch: SkillBranch::Rogue,
            level: 1,
            max_level: 5,
            mp_cost: 8,
            cooldown: 3,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::DotPoison(12, 4),
            description: "Coat your blade in venom, dealing 12 damage/turn for 4 turns.".to_string(),
            prerequisite: Some(11),
            unlocked: false,
            learned: false,
        },
        Skill {
            id: 14,
            name: "Phantom Step".to_string(),
            branch: SkillBranch::Rogue,
            level: 1,
            max_level: 3,
            mp_cost: 20,
            cooldown: 8,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::Stun(3),
            description: "Strike from the shadows, stunning the target for 3 turns.".to_string(),
            prerequisite: Some(12),
            unlocked: false,
            learned: false,
        },
        // ===== UNIVERSAL =====
        Skill {
            id: 15,
            name: "Meditation".to_string(),
            branch: SkillBranch::Universal,
            level: 1,
            max_level: 5,
            mp_cost: 0,
            cooldown: 5,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::MpHeal(30),
            description: "Restore 30 MP through focused meditation.".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
        },
        Skill {
            id: 16,
            name: "Lucky Star".to_string(),
            branch: SkillBranch::Universal,
            level: 1,
            max_level: 3,
            mp_cost: 0,
            cooldown: 0,
            current_cooldown: 0,
            is_passive: true,
            effect: SkillEffect::LuckBoost(10),
            description: "Permanently increases LUK by 10.".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
        },
        Skill {
            id: 17,
            name: "HP Regen".to_string(),
            branch: SkillBranch::Universal,
            level: 1,
            max_level: 5,
            mp_cost: 0,
            cooldown: 0,
            current_cooldown: 0,
            is_passive: true,
            effect: SkillEffect::PassiveRegenHp(2),
            description: "Regenerate 2 HP per turn.".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
        },
    ]
}
