use serde::{Deserialize, Serialize};

#[derive(Clone, PartialEq, Eq, Serialize, Deserialize, Debug)]
pub enum SkillBranch {
    Warrior,
    Mage,
    Rogue,
    Universal,
    Knight,
    Shaman,
    Alchemist,
}

#[derive(Clone, PartialEq, Eq, Serialize, Deserialize, Debug)]
pub enum SkillEffect {
    AttackMult(u32),        // percent multiplier (100 = normal)
    AoeDamage(i32),
    Heal(i32),
    MpHeal(i32),
    Shield(i32, u32),       // shield amount, turns
    DotPoison(i32, u32),    // damage per turn, turns
    Stun(u32),              // turns
    TeleportStrike,
    LifeSteal(u32),         // percent of damage
    SummonSkeleton,
    DoubleAttack,
    CritBoost(u32),         // percent crit rate boost
    MpReduce(u32),          // reduces mp costs
    ExpBoost(u32),          // exp multiplier
    LuckBoost(u32),
    PassiveAttackBoost(i32),
    PassiveDefBoost(i32),
    PassiveHpBoost(i32),
    PassiveMpBoost(i32),
    PassiveRegenHp(i32),
    PassiveRegenMp(i32),
    SoulDrain(i32),         // deal damage equal to i32% of base attack, heal player for same amount
    AttackBuff(i32, u32),   // boost player ATK by i32 for u32 turns
}

#[derive(Clone, Serialize, Deserialize, Debug)]
pub struct Skill {
    pub id: usize,
    pub name: String,
    pub branch: SkillBranch,
    pub level: u8,
    pub max_level: u8,
    pub mp_cost: i32,
    pub cooldown: u32,
    pub current_cooldown: u32,
    pub is_passive: bool,
    pub effect: SkillEffect,
    pub description: String,
    pub prerequisite: Option<usize>,
    pub unlocked: bool,
    pub learned: bool,
    pub sp_cost: u32,
}

impl Skill {
    pub fn can_use(&self, current_mp: i32) -> bool {
        !self.is_passive && self.learned && self.current_cooldown == 0 && current_mp >= self.mp_cost
    }
}

pub fn all_skills() -> Vec<Skill> {
    vec![
        // ===== WARRIOR BRANCH =====
        Skill {
            id: 0,
            name: "強打".to_string(),
            branch: SkillBranch::Warrior,
            level: 1,
            max_level: 5,
            mp_cost: 5,
            cooldown: 2,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::AttackMult(175),
            description: "175%ダメージを与える強力な一撃。".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
            sp_cost: 1,
        },
        Skill {
            id: 1,
            name: "鉄壁の盾".to_string(),
            branch: SkillBranch::Warrior,
            level: 1,
            max_level: 5,
            mp_cost: 8,
            cooldown: 5,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::Shield(30, 5),
            description: "5ターン間30ダメージを吸収するシールドを張る。".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
            sp_cost: 1,
        },
        Skill {
            id: 2,
            name: "狂戦士の怒り".to_string(),
            branch: SkillBranch::Warrior,
            level: 1,
            max_level: 3,
            mp_cost: 15,
            cooldown: 8,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::CritBoost(50),
            description: "5ターン間クリット率+50%の狂乱状態になる。".to_string(),
            prerequisite: Some(0),
            unlocked: false,
            learned: false,
            sp_cost: 2,
        },
        Skill {
            id: 3,
            name: "歴戦の肉体".to_string(),
            branch: SkillBranch::Warrior,
            level: 1,
            max_level: 5,
            mp_cost: 0,
            cooldown: 0,
            current_cooldown: 0,
            is_passive: true,
            effect: SkillEffect::PassiveHpBoost(50),
            description: "最大HPを50増加（パッシブ）。".to_string(),
            prerequisite: Some(1),
            unlocked: false,
            learned: false,
            sp_cost: 2,
        },
        Skill {
            id: 4,
            name: "武将の猛攻".to_string(),
            branch: SkillBranch::Warrior,
            level: 1,
            max_level: 3,
            mp_cost: 25,
            cooldown: 12,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::AoeDamage(40),
            description: "周囲の敵全員に40ダメージの衝撃波を放つ。".to_string(),
            prerequisite: Some(2),
            unlocked: false,
            learned: false,
            sp_cost: 3,
        },
        // ===== MAGE BRANCH =====
        Skill {
            id: 5,
            name: "火球".to_string(),
            branch: SkillBranch::Mage,
            level: 1,
            max_level: 5,
            mp_cost: 10,
            cooldown: 1,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::AoeDamage(25),
            description: "周囲の敵に25の魔法ダメージを与える火球を放つ。".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
            sp_cost: 1,
        },
        Skill {
            id: 6,
            name: "マナシールド".to_string(),
            branch: SkillBranch::Mage,
            level: 1,
            max_level: 5,
            mp_cost: 20,
            cooldown: 6,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::Shield(50, 8),
            description: "50ダメージを吸収するマナの障壁を生成。".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
            sp_cost: 1,
        },
        Skill {
            id: 7,
            name: "秘術の極意".to_string(),
            branch: SkillBranch::Mage,
            level: 1,
            max_level: 5,
            mp_cost: 0,
            cooldown: 0,
            current_cooldown: 0,
            is_passive: true,
            effect: SkillEffect::PassiveMpBoost(40),
            description: "最大MPを40増加（パッシブ）。".to_string(),
            prerequisite: Some(5),
            unlocked: false,
            learned: false,
            sp_cost: 2,
        },
        Skill {
            id: 8,
            name: "毒霧".to_string(),
            branch: SkillBranch::Mage,
            level: 1,
            max_level: 5,
            mp_cost: 18,
            cooldown: 4,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::DotPoison(8, 5),
            description: "5ターン間毎ターン8ダメージを与える毒霧を召喚。".to_string(),
            prerequisite: Some(5),
            unlocked: false,
            learned: false,
            sp_cost: 2,
        },
        Skill {
            id: 9,
            name: "魔力爆発".to_string(),
            branch: SkillBranch::Mage,
            level: 1,
            max_level: 3,
            mp_cost: 30,
            cooldown: 10,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::AttackMult(300),
            description: "全魔力を一点に集中させ300%ダメージの呪文を放つ。".to_string(),
            prerequisite: Some(7),
            unlocked: false,
            learned: false,
            sp_cost: 3,
        },
        // ===== ROGUE BRANCH =====
        Skill {
            id: 10,
            name: "影打ち".to_string(),
            branch: SkillBranch::Rogue,
            level: 1,
            max_level: 5,
            mp_cost: 6,
            cooldown: 2,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::TeleportStrike,
            description: "瞬間移動で敵の背後に回り必殺のクリティカル攻撃。".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
            sp_cost: 1,
        },
        Skill {
            id: 11,
            name: "剣舞".to_string(),
            branch: SkillBranch::Rogue,
            level: 1,
            max_level: 5,
            mp_cost: 10,
            cooldown: 3,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::DoubleAttack,
            description: "1ターンに2回攻撃。".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
            sp_cost: 1,
        },
        Skill {
            id: 12,
            name: "生命吸収".to_string(),
            branch: SkillBranch::Rogue,
            level: 1,
            max_level: 5,
            mp_cost: 0,
            cooldown: 0,
            current_cooldown: 0,
            is_passive: true,
            effect: SkillEffect::LifeSteal(20),
            description: "与ダメージの20%をHPとして吸収（パッシブ）。".to_string(),
            prerequisite: Some(10),
            unlocked: false,
            learned: false,
            sp_cost: 2,
        },
        Skill {
            id: 13,
            name: "毒刃".to_string(),
            branch: SkillBranch::Rogue,
            level: 1,
            max_level: 5,
            mp_cost: 8,
            cooldown: 3,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::DotPoison(12, 4),
            description: "刃を毒で覆い4ターン間毎ターン12ダメージを与える。".to_string(),
            prerequisite: Some(11),
            unlocked: false,
            learned: false,
            sp_cost: 2,
        },
        Skill {
            id: 14,
            name: "幻影歩法".to_string(),
            branch: SkillBranch::Rogue,
            level: 1,
            max_level: 3,
            mp_cost: 20,
            cooldown: 8,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::Stun(3),
            description: "影から奇襲し3ターン間対象をスタン状態にする。".to_string(),
            prerequisite: Some(12),
            unlocked: false,
            learned: false,
            sp_cost: 3,
        },
        // ===== UNIVERSAL =====
        Skill {
            id: 15,
            name: "瞑想".to_string(),
            branch: SkillBranch::Universal,
            level: 1,
            max_level: 5,
            mp_cost: 0,
            cooldown: 5,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::MpHeal(30),
            description: "集中した瞑想で30MPを回復。".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
            sp_cost: 1,
        },
        Skill {
            id: 16,
            name: "幸運の星".to_string(),
            branch: SkillBranch::Universal,
            level: 1,
            max_level: 3,
            mp_cost: 0,
            cooldown: 0,
            current_cooldown: 0,
            is_passive: true,
            effect: SkillEffect::LuckBoost(10),
            description: "LUKを永続的に10増加（パッシブ）。".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
            sp_cost: 1,
        },
        Skill {
            id: 17,
            name: "HP再生".to_string(),
            branch: SkillBranch::Universal,
            level: 1,
            max_level: 5,
            mp_cost: 0,
            cooldown: 0,
            current_cooldown: 0,
            is_passive: true,
            effect: SkillEffect::PassiveRegenHp(2),
            description: "毎ターン2HPを自動回復（パッシブ）。".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
            sp_cost: 1,
        },
        // ===== WARRIOR EXPANSION =====
        Skill {
            id: 18,
            name: "武器投擲".to_string(),
            branch: SkillBranch::Warrior,
            level: 1,
            max_level: 5,
            mp_cost: 8,
            cooldown: 3,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::AttackMult(200),
            description: "武器を投擲し敵に200%ダメージ。".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
            sp_cost: 1,
        },
        Skill {
            id: 19,
            name: "血の怒り".to_string(),
            branch: SkillBranch::Warrior,
            level: 1,
            max_level: 3,
            mp_cost: 12,
            cooldown: 6,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::CritBoost(40),
            description: "血の怒りに任せ6ターン間クリット率+40%。".to_string(),
            prerequisite: Some(18),
            unlocked: false,
            learned: false,
            sp_cost: 2,
        },
        Skill {
            id: 20,
            name: "鬨の声".to_string(),
            branch: SkillBranch::Warrior,
            level: 1,
            max_level: 3,
            mp_cost: 18,
            cooldown: 7,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::AoeDamage(30),
            description: "雄叫びを上げ周囲の敵に30ダメージ。".to_string(),
            prerequisite: Some(18),
            unlocked: false,
            learned: false,
            sp_cost: 2,
        },
        Skill {
            id: 21,
            name: "鉄の皮膚".to_string(),
            branch: SkillBranch::Warrior,
            level: 1,
            max_level: 5,
            mp_cost: 0,
            cooldown: 0,
            current_cooldown: 0,
            is_passive: true,
            effect: SkillEffect::PassiveDefBoost(15),
            description: "皮膚が鋼のように硬化、DEF+15（パッシブ）。".to_string(),
            prerequisite: Some(3),
            unlocked: false,
            learned: false,
            sp_cost: 2,
        },
        Skill {
            id: 22,
            name: "必殺の一撃".to_string(),
            branch: SkillBranch::Warrior,
            level: 1,
            max_level: 3,
            mp_cost: 30,
            cooldown: 14,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::AttackMult(450),
            description: "全力を一点に込め450%の必殺ダメージ。".to_string(),
            prerequisite: Some(4),
            unlocked: false,
            learned: false,
            sp_cost: 3,
        },
        // ===== MAGE EXPANSION =====
        Skill {
            id: 23,
            name: "氷の槍".to_string(),
            branch: SkillBranch::Mage,
            level: 1,
            max_level: 5,
            mp_cost: 12,
            cooldown: 3,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::AttackMult(180),
            description: "鋭い氷の槍を放ち180%ダメージ。".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
            sp_cost: 1,
        },
        Skill {
            id: 24,
            name: "雷の連鎖".to_string(),
            branch: SkillBranch::Mage,
            level: 1,
            max_level: 3,
            mp_cost: 22,
            cooldown: 5,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::AoeDamage(40),
            description: "連鎖する雷撃で周囲の敵に40ダメージ。".to_string(),
            prerequisite: Some(5),
            unlocked: false,
            learned: false,
            sp_cost: 2,
        },
        Skill {
            id: 25,
            name: "魔力吸収".to_string(),
            branch: SkillBranch::Mage,
            level: 1,
            max_level: 5,
            mp_cost: 0,
            cooldown: 6,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::MpHeal(50),
            description: "周囲の魔力を吸収し50MP回復。".to_string(),
            prerequisite: Some(6),
            unlocked: false,
            learned: false,
            sp_cost: 2,
        },
        Skill {
            id: 26,
            name: "マナの泉".to_string(),
            branch: SkillBranch::Mage,
            level: 1,
            max_level: 5,
            mp_cost: 0,
            cooldown: 0,
            current_cooldown: 0,
            is_passive: true,
            effect: SkillEffect::PassiveRegenMp(3),
            description: "毎ターン3MPを自動回復（パッシブ）。".to_string(),
            prerequisite: Some(7),
            unlocked: false,
            learned: false,
            sp_cost: 2,
        },
        Skill {
            id: 27,
            name: "次元斬".to_string(),
            branch: SkillBranch::Mage,
            level: 1,
            max_level: 3,
            mp_cost: 35,
            cooldown: 11,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::AttackMult(350),
            description: "次元を切り裂く350%の魔法攻撃。".to_string(),
            prerequisite: Some(9),
            unlocked: false,
            learned: false,
            sp_cost: 3,
        },
        // ===== ROGUE EXPANSION =====
        Skill {
            id: 28,
            name: "煙幕".to_string(),
            branch: SkillBranch::Rogue,
            level: 1,
            max_level: 5,
            mp_cost: 8,
            cooldown: 5,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::Shield(25, 3),
            description: "煙幕を張り3ターン間25ダメージを吸収。".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
            sp_cost: 1,
        },
        Skill {
            id: 29,
            name: "死の刻印".to_string(),
            branch: SkillBranch::Rogue,
            level: 1,
            max_level: 3,
            mp_cost: 10,
            cooldown: 5,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::CritBoost(35),
            description: "敵に死の刻印を刻み5ターン間クリット率+35%。".to_string(),
            prerequisite: Some(10),
            unlocked: false,
            learned: false,
            sp_cost: 2,
        },
        Skill {
            id: 30,
            name: "影の守護".to_string(),
            branch: SkillBranch::Rogue,
            level: 1,
            max_level: 5,
            mp_cost: 0,
            cooldown: 0,
            current_cooldown: 0,
            is_passive: true,
            effect: SkillEffect::PassiveAttackBoost(10),
            description: "影から攻撃する本能でATK+10（パッシブ）。".to_string(),
            prerequisite: Some(12),
            unlocked: false,
            learned: false,
            sp_cost: 2,
        },
        Skill {
            id: 31,
            name: "連続刺し".to_string(),
            branch: SkillBranch::Rogue,
            level: 1,
            max_level: 5,
            mp_cost: 14,
            cooldown: 4,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::DoubleAttack,
            description: "光速の連続刺しで2回攻撃。".to_string(),
            prerequisite: Some(11),
            unlocked: false,
            learned: false,
            sp_cost: 2,
        },
        Skill {
            id: 32,
            name: "急所狙い".to_string(),
            branch: SkillBranch::Rogue,
            level: 1,
            max_level: 3,
            mp_cost: 25,
            cooldown: 10,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::AttackMult(380),
            description: "急所を正確に貫き380%の致命ダメージ。".to_string(),
            prerequisite: Some(29),
            unlocked: false,
            learned: false,
            sp_cost: 3,
        },
        // ===== KNIGHT 騎士 =====
        Skill {
            id: 33,
            name: "挑発".to_string(),
            branch: SkillBranch::Knight,
            level: 1,
            max_level: 5,
            mp_cost: 6,
            cooldown: 4,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::Shield(20, 4),
            description: "挑発で敵の攻撃を引きつけ4ターン間20ダメージ吸収。".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
            sp_cost: 1,
        },
        Skill {
            id: 34,
            name: "反撃".to_string(),
            branch: SkillBranch::Knight,
            level: 1,
            max_level: 5,
            mp_cost: 8,
            cooldown: 4,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::AttackMult(160),
            description: "敵の攻撃に合わせ160%の反撃を繰り出す。".to_string(),
            prerequisite: Some(33),
            unlocked: false,
            learned: false,
            sp_cost: 2,
        },
        Skill {
            id: 35,
            name: "聖なる盾".to_string(),
            branch: SkillBranch::Knight,
            level: 1,
            max_level: 5,
            mp_cost: 20,
            cooldown: 8,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::Shield(70, 7),
            description: "聖なる力で70ダメージを吸収する盾を7ターン張る。".to_string(),
            prerequisite: Some(33),
            unlocked: false,
            learned: false,
            sp_cost: 2,
        },
        Skill {
            id: 36,
            name: "重鎧の極意".to_string(),
            branch: SkillBranch::Knight,
            level: 1,
            max_level: 5,
            mp_cost: 0,
            cooldown: 0,
            current_cooldown: 0,
            is_passive: true,
            effect: SkillEffect::PassiveDefBoost(25),
            description: "重鎧を極め DEF+25（パッシブ）。".to_string(),
            prerequisite: Some(35),
            unlocked: false,
            learned: false,
            sp_cost: 2,
        },
        Skill {
            id: 37,
            name: "裁きの一撃".to_string(),
            branch: SkillBranch::Knight,
            level: 1,
            max_level: 3,
            mp_cost: 28,
            cooldown: 9,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::AoeDamage(55),
            description: "聖なる力を解放し周囲の敵に55ダメージ。".to_string(),
            prerequisite: Some(34),
            unlocked: false,
            learned: false,
            sp_cost: 2,
        },
        Skill {
            id: 38,
            name: "聖域".to_string(),
            branch: SkillBranch::Knight,
            level: 1,
            max_level: 5,
            mp_cost: 25,
            cooldown: 10,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::Heal(60),
            description: "聖域を展開し60HP回復。".to_string(),
            prerequisite: Some(36),
            unlocked: false,
            learned: false,
            sp_cost: 3,
        },
        Skill {
            id: 39,
            name: "神の加護".to_string(),
            branch: SkillBranch::Knight,
            level: 1,
            max_level: 5,
            mp_cost: 0,
            cooldown: 0,
            current_cooldown: 0,
            is_passive: true,
            effect: SkillEffect::PassiveHpBoost(100),
            description: "神の加護により最大HP+100（パッシブ）。".to_string(),
            prerequisite: Some(37),
            unlocked: false,
            learned: false,
            sp_cost: 3,
        },
        // ===== SHAMAN 呪術師 =====
        Skill {
            id: 40,
            name: "呪い".to_string(),
            branch: SkillBranch::Shaman,
            level: 1,
            max_level: 5,
            mp_cost: 10,
            cooldown: 4,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::DotPoison(6, 8),
            description: "呪いをかけ8ターン間毎ターン6ダメージ。".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
            sp_cost: 1,
        },
        Skill {
            id: 41,
            name: "憑依".to_string(),
            branch: SkillBranch::Shaman,
            level: 1,
            max_level: 3,
            mp_cost: 15,
            cooldown: 6,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::Stun(2),
            description: "敵に悪霊を憑依させ2ターンスタン。".to_string(),
            prerequisite: Some(40),
            unlocked: false,
            learned: false,
            sp_cost: 2,
        },
        Skill {
            id: 42,
            name: "魂の吸収".to_string(),
            branch: SkillBranch::Shaman,
            level: 1,
            max_level: 5,
            mp_cost: 18,
            cooldown: 5,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::SoulDrain(120),
            description: "敵の魂を吸収し120%ダメージ＋同量HP回復。".to_string(),
            prerequisite: Some(40),
            unlocked: false,
            learned: false,
            sp_cost: 2,
        },
        Skill {
            id: 43,
            name: "呪いの加護".to_string(),
            branch: SkillBranch::Shaman,
            level: 1,
            max_level: 3,
            mp_cost: 0,
            cooldown: 0,
            current_cooldown: 0,
            is_passive: true,
            effect: SkillEffect::LuckBoost(15),
            description: "呪いを利用しLUK+15（パッシブ）。".to_string(),
            prerequisite: Some(41),
            unlocked: false,
            learned: false,
            sp_cost: 2,
        },
        Skill {
            id: 44,
            name: "不死の呼び声".to_string(),
            branch: SkillBranch::Shaman,
            level: 1,
            max_level: 3,
            mp_cost: 20,
            cooldown: 8,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::SummonSkeleton,
            description: "骸骨を召喚し共に戦う。".to_string(),
            prerequisite: Some(41),
            unlocked: false,
            learned: false,
            sp_cost: 2,
        },
        Skill {
            id: 45,
            name: "霊縛".to_string(),
            branch: SkillBranch::Shaman,
            level: 1,
            max_level: 3,
            mp_cost: 28,
            cooldown: 12,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::Stun(4),
            description: "敵の霊魂を縛り4ターン完全スタン。".to_string(),
            prerequisite: Some(44),
            unlocked: false,
            learned: false,
            sp_cost: 3,
        },
        Skill {
            id: 46,
            name: "暗黒の儀式".to_string(),
            branch: SkillBranch::Shaman,
            level: 1,
            max_level: 3,
            mp_cost: 35,
            cooldown: 13,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::AttackMult(300),
            description: "己の生命力を代償に300%の暗黒魔法。".to_string(),
            prerequisite: Some(43),
            unlocked: false,
            learned: false,
            sp_cost: 3,
        },
        // ===== ALCHEMIST 錬金術師 =====
        Skill {
            id: 47,
            name: "薬の達人".to_string(),
            branch: SkillBranch::Alchemist,
            level: 1,
            max_level: 5,
            mp_cost: 12,
            cooldown: 4,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::Heal(55),
            description: "錬成した薬で55HP回復。".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
            sp_cost: 1,
        },
        Skill {
            id: 48,
            name: "爆炎瓶".to_string(),
            branch: SkillBranch::Alchemist,
            level: 1,
            max_level: 3,
            mp_cost: 20,
            cooldown: 6,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::AoeDamage(50),
            description: "爆炎瓶を投げ周囲の敵に50ダメージ。".to_string(),
            prerequisite: Some(47),
            unlocked: false,
            learned: false,
            sp_cost: 2,
        },
        Skill {
            id: 49,
            name: "酸の飛沫".to_string(),
            branch: SkillBranch::Alchemist,
            level: 1,
            max_level: 5,
            mp_cost: 16,
            cooldown: 5,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::DotPoison(18, 5),
            description: "強酸を浴びせ5ターン間毎ターン18ダメージ。".to_string(),
            prerequisite: Some(47),
            unlocked: false,
            learned: false,
            sp_cost: 2,
        },
        Skill {
            id: 50,
            name: "黄金変換".to_string(),
            branch: SkillBranch::Alchemist,
            level: 1,
            max_level: 3,
            mp_cost: 0,
            cooldown: 0,
            current_cooldown: 0,
            is_passive: true,
            effect: SkillEffect::ExpBoost(130),
            description: "物質を黄金に変える知識でEXP+30%（パッシブ）。".to_string(),
            prerequisite: Some(48),
            unlocked: false,
            learned: false,
            sp_cost: 2,
        },
        Skill {
            id: 51,
            name: "武器強化".to_string(),
            branch: SkillBranch::Alchemist,
            level: 1,
            max_level: 5,
            mp_cost: 0,
            cooldown: 0,
            current_cooldown: 0,
            is_passive: true,
            effect: SkillEffect::PassiveAttackBoost(18),
            description: "武器を錬金術で強化しATK+18（パッシブ）。".to_string(),
            prerequisite: Some(48),
            unlocked: false,
            learned: false,
            sp_cost: 2,
        },
        Skill {
            id: 52,
            name: "媒介の秘薬".to_string(),
            branch: SkillBranch::Alchemist,
            level: 1,
            max_level: 5,
            mp_cost: 0,
            cooldown: 7,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::MpHeal(65),
            description: "最高品質の秘薬でMP65回復。".to_string(),
            prerequisite: Some(50),
            unlocked: false,
            learned: false,
            sp_cost: 3,
        },
        Skill {
            id: 53,
            name: "賢者の石".to_string(),
            branch: SkillBranch::Alchemist,
            level: 1,
            max_level: 5,
            mp_cost: 0,
            cooldown: 0,
            current_cooldown: 0,
            is_passive: true,
            effect: SkillEffect::PassiveMpBoost(60),
            description: "賢者の石の力で最大MP+60（パッシブ）。".to_string(),
            prerequisite: Some(52),
            unlocked: false,
            learned: false,
            sp_cost: 3,
        },
    ]
}
