use serde::{Deserialize, Serialize};

#[derive(Clone, PartialEq, Eq, Serialize, Deserialize, Debug)]
pub enum SkillBranch {
    Warrior,
    Mage,
    Rogue,
    Universal,
}

#[derive(Clone, PartialEq, Eq, Serialize, Deserialize, Debug)]
pub enum SkillEffect {
    AttackMult(u32),        // percent multiplier (100 = normal)
    AoeDamage(i32),
    Heal(i32),
    MpHeal(i32),
    Shield(i32, u32),       // shield amount, turns
    DotPoison(i32, u32),    // damage per turn, turns
    Stun(u32),              // turns
    TeleportStrike,
    LifeSteal(u32),         // percent of damage
    SummonSkeleton,
    DoubleAttack,
    CritBoost(u32),         // percent crit rate boost
    MpReduce(u32),          // reduces mp costs
    ExpBoost(u32),          // exp multiplier
    LuckBoost(u32),
    PassiveAttackBoost(i32),
    PassiveDefBoost(i32),
    PassiveHpBoost(i32),
    PassiveMpBoost(i32),
    PassiveRegenHp(i32),
    PassiveRegenMp(i32),
}

#[derive(Clone, Serialize, Deserialize, Debug)]
pub struct Skill {
    pub id: usize,
    pub name: String,
    pub branch: SkillBranch,
    pub level: u8,
    pub max_level: u8,
    pub mp_cost: i32,
    pub cooldown: u32,
    pub current_cooldown: u32,
    pub is_passive: bool,
    pub effect: SkillEffect,
    pub description: String,
    pub prerequisite: Option<usize>,
    pub unlocked: bool,
    pub learned: bool,
}

impl Skill {
    pub fn can_use(&self, current_mp: i32) -> bool {
        !self.is_passive && self.learned && self.current_cooldown == 0 && current_mp >= self.mp_cost
    }
}

pub fn all_skills() -> Vec<Skill> {
    vec![
        // ===== WARRIOR BRANCH =====
        Skill {
            id: 0,
            name: "強打".to_string(),
            branch: SkillBranch::Warrior,
            level: 1,
            max_level: 5,
            mp_cost: 5,
            cooldown: 2,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::AttackMult(175),
            description: "175%ダメージを与える強力な一撃。".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
        },
        Skill {
            id: 1,
            name: "鉄壁の盾".to_string(),
            branch: SkillBranch::Warrior,
            level: 1,
            max_level: 5,
            mp_cost: 8,
            cooldown: 5,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::Shield(30, 5),
            description: "5ターン間30ダメージを吸収するシールドを張る。".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
        },
        Skill {
            id: 2,
            name: "狂戦士の怒り".to_string(),
            branch: SkillBranch::Warrior,
            level: 1,
            max_level: 3,
            mp_cost: 15,
            cooldown: 8,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::CritBoost(50),
            description: "5ターン間クリット率+50%の狂乱状態になる。".to_string(),
            prerequisite: Some(0),
            unlocked: false,
            learned: false,
        },
        Skill {
            id: 3,
            name: "歴戦の肉体".to_string(),
            branch: SkillBranch::Warrior,
            level: 1,
            max_level: 5,
            mp_cost: 0,
            cooldown: 0,
            current_cooldown: 0,
            is_passive: true,
            effect: SkillEffect::PassiveHpBoost(50),
            description: "最大HPを50増加（パッシブ）。".to_string(),
            prerequisite: Some(1),
            unlocked: false,
            learned: false,
        },
        Skill {
            id: 4,
            name: "武将の猛攻".to_string(),
            branch: SkillBranch::Warrior,
            level: 1,
            max_level: 3,
            mp_cost: 25,
            cooldown: 12,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::AoeDamage(40),
            description: "周囲の敵全員に40ダメージの衝撃波を放つ。".to_string(),
            prerequisite: Some(2),
            unlocked: false,
            learned: false,
        },
        // ===== MAGE BRANCH =====
        Skill {
            id: 5,
            name: "火球".to_string(),
            branch: SkillBranch::Mage,
            level: 1,
            max_level: 5,
            mp_cost: 10,
            cooldown: 1,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::AoeDamage(25),
            description: "周囲の敵に25の魔法ダメージを与える火球を放つ。".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
        },
        Skill {
            id: 6,
            name: "マナシールド".to_string(),
            branch: SkillBranch::Mage,
            level: 1,
            max_level: 5,
            mp_cost: 20,
            cooldown: 6,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::Shield(50, 8),
            description: "50ダメージを吸収するマナの障壁を生成。".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
        },
        Skill {
            id: 7,
            name: "秘術の極意".to_string(),
            branch: SkillBranch::Mage,
            level: 1,
            max_level: 5,
            mp_cost: 0,
            cooldown: 0,
            current_cooldown: 0,
            is_passive: true,
            effect: SkillEffect::PassiveMpBoost(40),
            description: "最大MPを40増加（パッシブ）。".to_string(),
            prerequisite: Some(5),
            unlocked: false,
            learned: false,
        },
        Skill {
            id: 8,
            name: "毒霧".to_string(),
            branch: SkillBranch::Mage,
            level: 1,
            max_level: 5,
            mp_cost: 18,
            cooldown: 4,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::DotPoison(8, 5),
            description: "5ターン間毎ターン8ダメージを与える毒霧を召喚。".to_string(),
            prerequisite: Some(5),
            unlocked: false,
            learned: false,
        },
        Skill {
            id: 9,
            name: "魔力爆発".to_string(),
            branch: SkillBranch::Mage,
            level: 1,
            max_level: 3,
            mp_cost: 30,
            cooldown: 10,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::AttackMult(300),
            description: "全魔力を一点に集中させ300%ダメージの呪文を放つ。".to_string(),
            prerequisite: Some(7),
            unlocked: false,
            learned: false,
        },
        // ===== ROGUE BRANCH =====
        Skill {
            id: 10,
            name: "影打ち".to_string(),
            branch: SkillBranch::Rogue,
            level: 1,
            max_level: 5,
            mp_cost: 6,
            cooldown: 2,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::TeleportStrike,
            description: "瞬間移動で敵の背後に回り必殺のクリティカル攻撃。".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
        },
        Skill {
            id: 11,
            name: "剣舞".to_string(),
            branch: SkillBranch::Rogue,
            level: 1,
            max_level: 5,
            mp_cost: 10,
            cooldown: 3,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::DoubleAttack,
            description: "1ターンに2回攻撃。".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
        },
        Skill {
            id: 12,
            name: "生命吸収".to_string(),
            branch: SkillBranch::Rogue,
            level: 1,
            max_level: 5,
            mp_cost: 0,
            cooldown: 0,
            current_cooldown: 0,
            is_passive: true,
            effect: SkillEffect::LifeSteal(20),
            description: "与ダメージの20%をHPとして吸収（パッシブ）。".to_string(),
            prerequisite: Some(10),
            unlocked: false,
            learned: false,
        },
        Skill {
            id: 13,
            name: "毒刃".to_string(),
            branch: SkillBranch::Rogue,
            level: 1,
            max_level: 5,
            mp_cost: 8,
            cooldown: 3,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::DotPoison(12, 4),
            description: "刃を毒で覆い4ターン間毎ターン12ダメージを与える。".to_string(),
            prerequisite: Some(11),
            unlocked: false,
            learned: false,
        },
        Skill {
            id: 14,
            name: "幻影歩法".to_string(),
            branch: SkillBranch::Rogue,
            level: 1,
            max_level: 3,
            mp_cost: 20,
            cooldown: 8,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::Stun(3),
            description: "影から奇襲し3ターン間対象をスタン状態にする。".to_string(),
            prerequisite: Some(12),
            unlocked: false,
            learned: false,
        },
        // ===== UNIVERSAL =====
        Skill {
            id: 15,
            name: "瞑想".to_string(),
            branch: SkillBranch::Universal,
            level: 1,
            max_level: 5,
            mp_cost: 0,
            cooldown: 5,
            current_cooldown: 0,
            is_passive: false,
            effect: SkillEffect::MpHeal(30),
            description: "集中した瞑想で30MPを回復。".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
        },
        Skill {
            id: 16,
            name: "幸運の星".to_string(),
            branch: SkillBranch::Universal,
            level: 1,
            max_level: 3,
            mp_cost: 0,
            cooldown: 0,
            current_cooldown: 0,
            is_passive: true,
            effect: SkillEffect::LuckBoost(10),
            description: "LUKを永続的に10増加（パッシブ）。".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
        },
        Skill {
            id: 17,
            name: "HP再生".to_string(),
            branch: SkillBranch::Universal,
            level: 1,
            max_level: 5,
            mp_cost: 0,
            cooldown: 0,
            current_cooldown: 0,
            is_passive: true,
            effect: SkillEffect::PassiveRegenHp(2),
            description: "毎ターン2HPを自動回復（パッシブ）。".to_string(),
            prerequisite: None,
            unlocked: true,
            learned: false,
        },
    ]
}
